version: "2.1"
services:
  plexconverter:
    container_name: plexconverter
    image: plexconverter:latest
    build:
      context: /path/to/config/plexconverter
      dockerfile: plexconverter.Dockerfile
    user: 1001:100 # plex user:users group
    command: /bin/sh -c "python PlexConverter-headless/converter.py"
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - VIDEO_CRF=27
      - VIDEO_MAX_BITRATE=2750
      - FOR_WIDTH=1920
      - FOR_HEIGHT=1080
      - AUDIO_MAX_BITRATE=256
      - RADARR_FOLDER=radarr
      - SONARR_FOLDER=sonarr
    volumes:
      - /path/to/downloads:/downloads
