version: "2.1"
services:
  plexconverter:
    container_name: plexconverter
    image: plexconverter:latest
    build:
      context: /path/to/config/plexconverter/PlexConverter-headless
    user: 1001:100 # plex user:users group
    command: /bin/sh -c "python /config/PlexConverter-headless/converter.py"
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - VIDEO_CRF=25
      - VIDEO_MAX_BITRATE=3500
      - AUDIO_MAX_BITRATE=256
      - RADARR_FOLDER=radarr
      - SONARR_FOLDER=sonarr
      - FOR_WIDTH=1920
      - FOR_HEIGHT=1080
    volumes:
      - /path/to/config:/config
      - /path/to/downloads:/downloads
