version: "2.1"
services:
  plexconverter:
    container_name: plexconverter
    build: .
    command: /bin/sh -c "python PlexConverter-headless/converter.py"
    restart: unless-stopped
    user: 1001:100
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - MAX_VIDEO_WIDTH=1280
      - MAX_VIDEO_HEIGHT=720
      - AVERAGE_BITRATE=1100
      - MAX_BITRATE=1600
    volumes:
      - /path/to/downloads/complete:/downloads
      - /path/to/config/plexconverter/converted:/converted
      - /path/to/config/plexconverter/normalized:/normalized
      - /path/to/downloads/optimized:/optimized
